MyCal: MyCal.m main.m
	clang -fobjc-arc -framework Foundation MyCal.m main.m -o MyCal
run:
	./MyCal
	./MyCal 11 2013
	./MyCal -m 11
	./MyCal 2013
	./MyCal 0
	./MyCal 10 a
	./MyCal a 2013
	./MyCal -m a
	./MyCal -f 10
	./MyCal 10 2013 2013
clean:
	rm MyCal
